### ISSUE TITLE
Flatpak version does not reconize system firefox

### ISSUE THREAD

**Issue by wiiznokes** [cosmic-utils/web-apps#60]
Why not give the flatpak app the permission to read `/usr/share/applications/`?

**Comment by elevenhsoft** [comment]
To be honest. I did not know we can give permission to this directory. Actually reading it and parsing each desktop entry should give as view on installed browsers. Maybe it's not a bad idea.

**Comment by wiiznokes** [comment]
I think it will work. For example, for my app `fan-control`, i was able to read `/sys`

**Comment by elevenhsoft** [comment]
From now: https://github.com/cosmic-utils/web-apps/commit/248e24d4670768ca7458ce5f0b486b382076f760 we will read installed browsers from freedesktop entries.

After setting proper permissions for flatpak, we should be able to read also system browsers. This should solve this issue. 
I must test this more :P

**Comment by elevenhsoft** [comment]
Also hope, flathub maintainers will agree with permissions, anyway it's only read access so... not big deal I guess ^^

**Comment by wiiznokes** [comment]
> From now: https://github.com/cosmic-utils/web-apps/commit/248e24d4670768ca7458ce5f0b486b382076f760 we will read installed browsers from freedesktop entries.

Maybe you could read the `Category` field for `Browser` to support more browser. Tho, it will probably not be compatible with profiles

**Comment by wiiznokes** [comment]
> Also hope, flathub maintainers will agree with permissions, anyway it's only read access so... not big deal I guess ^^

Wait, you have to ask to use permission ?? i thought you could put anything in there

**Comment by elevenhsoft** [comment]
> Tho, it will probably not be compatible with profiles

Yeah that's the real problem. We must know what browser we are going to use. Just for profiles and some other settings like navbar, incognito etc.

> Wait, you have to ask to use permission ?? i thought you could put anything in there

Yes and no ^^ You can put anything until they found what you put and stop your PR. Also when you are changing permission you will be verified in most cases again. 
Check this out: https://github.com/flathub/io.github.elevenhsoft.WebApps/issues/5

**Comment by wiiznokes** [comment]
Oh I see. I hope it will get accepted then but just a read in the dir is fine imo

**Comment by elevenhsoft** [comment]
It's read only access needed so should be fine. But improvement is fine :)

**Comment by elevenhsoft** [comment]
Well, I'm stuck. Tried different filesystem permissions and it can't find any browser at all :rofl: 
Setting directly `/usr/share/applications:ro` it complain about `/usr` is restricted or something.

**Comment by elevenhsoft** [comment]
Ah well, it's mounted in `/run/host` so this is not included in: https://github.com/pop-os/freedesktop-desktop-entry/blob/main/src/lib.rs#L417-L424

Damn....

**Comment by elevenhsoft** [comment]
Got it sorted somehow. It's not perfect but it works. Just noticed one more bug and tomorrow probably will push it to flathub. Hope they will agree with elevated permissions :P

**Comment by wiiznokes** [comment]
Looking forward to test the flatpak version

**Comment by elevenhsoft** [comment]
Ok, so update pushed and the app is already on flathub :)

**Comment by wiiznokes** [comment]
Great! Just wanted to let you know you can change the just prefix like this: `just prefix="/app" install`

**Comment by elevenhsoft** [comment]
Yeah, I noticed it but later, after my hassle with sed :P
Anyway, now we are got rid of it, since we can use Cosmic's BaseApp.

Hope system browsers will works for you^^

**Comment by wiiznokes** [comment]
![Capture d’écran du 2024-10-09 16-26-49](https://github.com/user-attachments/assets/2f631213-de98-4288-ab29-00151d8b6f33)

sadly it doesn't show my firefox :cry:

**Comment by elevenhsoft** [comment]
What distro? And where is firefox.desktop file stored. We are using now `freedesktop-desktop-entry` but for flatpak, that is kind of different. We are looking only into those directories: https://github.com/cosmic-utils/web-apps/blob/master/src/browser.rs#L105-L108

Oh well, I forgot about `~/.local/share/applications` maybe there you have firefox.desktop file.

Current approach is well.... bad :P I will think about something better but let's be honest. Working in flatpak sandbox is not butter smooth because of permissions and I'm not familiar with it. However we are now have `host-os` permission so we can look into more paths. But still, they are mounted in different paths so this crate mentioned earlier can't find those desktop files and so on. Pain :P

But, let's back to questions. What distro? And where is firefox.desktop file stored. :)

**Comment by wiiznokes** [comment]
> What distro? And where is firefox.desktop file stored.

Fedora,

```
> ls /usr/share/applications/org.mozilla.firefox.desktop 
/usr/share/applications/org.mozilla.firefox.desktop
```

I will try to debug it when i've got time, no worries :)

**Comment by elevenhsoft** [comment]
Ok. So it's id is `org.mozilla.firefox` and we comparing it to: https://github.com/cosmic-utils/web-apps/blob/master/src/supported_browsers.rs#L9 here https://github.com/cosmic-utils/web-apps/blob/master/src/browser.rs#L157-L162

That's why it's fail. Probably my approach is kind of stupid to do this thing, or we should add another browser id but in the future it will generate another issues like this.

I will think of it.

And also, thanks for your interest, much appreciated :)

**Comment by elevenhsoft** [comment]
Ok, so I changed it a bit: https://github.com/cosmic-utils/web-apps/commit/aa17aaf87bd4941abd82ab166accb886b364b227

We will check if found exec string in desktop file contains our executable name, so it should catch more browsers. And it should works also in your case. Also we will recognize if app is installed "Locally" or "System-wide". So user will know what binary is found. Currently it does not matter if we choose local binary or system, it will run for example `firefox`, so first found executable in system. Probably it will be local. Maybe I should remove duplicates and it will be better. I don't know yet. Anyway, not big deal. I just found it Pop_OS have local desktop file for firefox as well as system. So it is found as double.

**Comment by elevenhsoft** [comment]
I will test how flatpak will behave, also please do some test if you can on your system. Would be nice :)

If everything will goes ok i will update flathub.

**Comment by wiiznokes** [comment]
Can you like a PR in flathub for a test repo ?

**Comment by wiiznokes** [comment]
I work now, that you so much!
