### ISSUE TITLE
Hanging url bar

### ISSUE THREAD

**Issue by NikunjVashishtha** [cosmic-utils/web-apps#69]
![image](https://github.com/user-attachments/assets/d791f3a4-5a01-441c-a111-811a7a156d17)
Seeing this hanging url bar suddenly, it didn't show this way before and worked perfectly fine. Probably a glitch?
Btw thx to the creator, awesome app; sort of best ive found so far.

**Comment by NikunjVashishtha** [comment]
Tried downgrading to lower version but no luck, maybe it's due to some changes with Firefox updates, could u please fix this?

**Comment by elevenhsoft** [comment]
Hey, thanks for your report :)

It's probably due to some changes in firefox. I doubt it's a web apps issue. I will look into it :)

**Comment by elevenhsoft** [comment]
Ok, so the issue was because of this CSS rule in userChrome.css:

```
#nav-bar * {
    visibility: visible !important;
```

what is interesting, previously it was working so I assume something changed in recent versions of firefox.

I will push to flathub as fast as possible. Probably today on the evening :)

The fix: https://github.com/cosmic-utils/web-apps/commit/c6f93b4c1b6698b95968457a4d321c97099fd5e0

**Comment by NikunjVashishtha** [comment]
Cool!
